"""empty message

Revision ID: a96b9f7c0b5d
Revises: 5c0ab5907860
Create Date: 2022-04-30 19:02:19.824810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a96b9f7c0b5d'
down_revision = '5c0ab5907860'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fav_planets', sa.Column('id_user', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'fav_planets', 'user', ['id_user'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fav_planets', type_='foreignkey')
    op.drop_column('fav_planets', 'id_user')
    # ### end Alembic commands ###
